'use client';
import { getLocalStorage, setLocalStorage } from '../lib/storageHelper';
import { useState, useEffect } from 'react';
import {Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, Button, useDisclosure} from "@nextui-org/react";

export default function CookieBanner(){
    const {isOpen, onOpen, onClose} = useDisclosure();
    const [cookieConsent, setCookieConsent] = useState<boolean>();

    useEffect (() => {
        const storedCookieConsent = getLocalStorage("cookie_consent", null);
        setCookieConsent(storedCookieConsent);
    }, [setCookieConsent]);

    useEffect(() => {
        const newValue = cookieConsent ? 'granted' : 'denied';

        window.gtag("consent", 'update', {
            'analytics_storage': newValue
        });

        if (cookieConsent){
            setLocalStorage("cookie_consent", cookieConsent);
        }

    }, [cookieConsent,setCookieConsent]);

    return (
        <div>
            {(cookieConsent == null || undefined) && (
                <div className={`my-10 mx-auto max-w-max md:max-w-screen-sm
                            fixed bottom-0 left-0 right-0 flex
                            px-3 md:px-4 py-3 justify-between items-center 
                            flex-col sm:flex-row gap-4  
                            bg-gray-700 rounded-lg shadow`}>

                    <button className='text-gray-300 cursor-pointer' onClick={onOpen}>
                        We use <span style={{ color: '#7fb3d5' }}>cookies</span> on our site.
                    </button>

                    <div className='flex gap-2'>
                        <button className='px-5 py-2 text-gray-300 rounded-md border-gray-900' onClick={() => setCookieConsent(false)}>Decline</button>
                        <button className='bg-gray-900 px-5 py-2 text-white rounded-lg' onClick={() => setCookieConsent(true)}>Allow Cookies</button>
                    </div>
                    <Modal isOpen={isOpen} onClose={onClose} scrollBehavior={"inside"}>
                        <ModalContent>
                            <ModalHeader className="flex flex-col gap-1">Cookie Policy</ModalHeader>
                            <ModalBody>
                                <h5>Privacy Policy for Rustic Italian Trattoria</h5>
                                <h5>1. Introduction</h5>
                                <p>Welcome to Rustic Italian Trattoria! This privacy policy explains how we collect, use, and protect your personal information when you use our website. By using our website, you agree to the terms outlined in this policy.</p>
                                <h5>2. Information We Collect</h5>
                                <p>We may collect the following types of information when you visit our website:</p>
                                <h6>2.1. Personal Information:</h6>
                                <p>This may include your name, email address, and other contact details that you voluntarily provide when subscribing to our newsletter or contacting us through forms on our website.</p>
                                <h6>2.2. Automatically Collected Information: </h6>
                                <p>We use Google Analytics, a web analytics service provided by Google, Inc. Google. Google Analytics uses cookies to help analyze how users interact with the site. The information generated by the cookie about your use of the website including your IP address will be transmitted to and stored by Google on servers in the United States.</p>
                                <h5>3. Google Analytics and GDPR Compliance</h5>
                                <p>We use Google Analytics to analyze the use of our website. Google Analytics gathers information about website use through cookies. The data collected by Google Analytics is used to create reports about the use of our website. Google privacy policy is available at: Google Privacy & Terms.</p>
                                <p>To comply with GDPR, we have implemented the following measures:</p>
                                <h6>3.1. IP Anonymization:</h6>
                                <p>We have enabled IP anonymization in Google Analytics, meaning that your IP address will be truncated by Google within member states of the European Union or other parties to the Agreement on the European Economic Area before being transmitted to the United States.</p>
                                <h6>3.2. Data Processing Amendment:</h6>
                                <p>We have signed a data processing amendment with Google Analytics to ensure that the processing of data is in compliance with GDPR.</p>
                                <h5>4. Your Choices</h5>
                                <p>You can refuse the use of cookies by selecting the appropriate settings on your browser. However, please note that if you do this, you may not be able to use the full functionality of our website.</p>
                                <h5>5. Security</h5>
                                <p>We take reasonable measures to protect your personal information from unauthorized access or disclosure.</p>
                                <h5>6. Changes to this Privacy Policy</h5>
                                <p>We may update this privacy policy from time to time. The date of the latest revision will be indicated at the top of this page. We encourage you to review this page regularly to stay informed about our data practices.</p>
                                <h5>7. Contact Us</h5>
                                <p>If you have any questions about this privacy policy or our data practices, please contact us at our email.</p>
                            </ModalBody>
                            <ModalFooter>
                                <Button color="danger" variant="light" onPress={onClose}>
                                    Close
                                </Button>
                            </ModalFooter>
                        </ModalContent>
                    </Modal>   
                </div>
            )}
        </div>
    )
}
