import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GoogleAnalytics from './components/googleAnalytics';
import CookieBanner from './components/cookieBanner';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GoogleAnalytics GA_MEASUREMENT_ID="G-FX58PLBH7Y"/>
      <body className={inter.className}>
        {children}
        <CookieBanner/>
      </body>
    </html>
  )
}
