import type { Metadata } from 'next'
import GoogleAnalytics from './components/googleAnalytics';
import CookieBanner from './components/cookieBanner';
import {Providers} from "./providers";
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GoogleAnalytics GA_MEASUREMENT_ID="G-FX58PLBH7Y"/>
      <body>
        <Providers>
          {children}
          <CookieBanner/>
        </Providers>
      </body>
    </html>
  )
}
